version: '3.8'

services:
  bluesky-connector:
    build:
      context: .
      args:
        SERVER_PORT: ${SERVER_PORT}
      tags:
        - "bluesky-connector:latest"
    image: bluesky-connector:latest
    container_name: bluesky-connector
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${SERVER_PORT}/bluesky/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - LOG_LEVEL=info
    volumes:
      - ./logs:/app/logs
    networks:
      - think-root-network

networks:
  think-root-network:
    external: true